"""empty message

Revision ID: e1d9460d7855
Revises: d1f33e1b0038
Create Date: 2025-09-24 20:43:29.745447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e1d9460d7855'
down_revision: Union[str, Sequence[str], None] = 'd1f33e1b0038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None




def safe_drop_constraint(constraint_name, table_name, type_='foreignkey'):
    try:
        op.drop_constraint(constraint_name, table_name, type_=type_)
    except Exception:
        pass

def safe_drop_index(index_name, table_name):
    try:
        op.drop_index(index_name, table_name=table_name)
    except Exception:
        pass

def safe_drop_table(table_name):
    try:
        op.drop_table(table_name)
    except Exception:
        pass

def upgrade():
    safe_drop_constraint('dipendente_cliente_ibfk_1', 'dipendente_cliente')
    safe_drop_constraint('dipendente_cliente_ibfk_2', 'dipendente_cliente')
    safe_drop_constraint('dipendente_servizio_ibfk_1', 'dipendente_servizio')
    safe_drop_constraint('dipendente_servizio_ibfk_2', 'dipendente_servizio')
    safe_drop_constraint('fk_notai_dipendente', 'notai')
    safe_drop_constraint('servizio_documentazione_ibfk_2', 'servizio_documentazione')
    safe_drop_constraint('servizio_documentazione_ibfk_1', 'servizio_documentazione')
    safe_drop_constraint('dipendenti_tecnici_ibfk_1', 'dipendenti_tecnici')
    safe_drop_index('dipendente_id', 'dipendente_cliente')
    safe_drop_index('cliente_id', 'dipendente_cliente')
    safe_drop_table('dipendente_cliente')
    safe_drop_index('dipendente_id', 'dipendente_servizio')
    safe_drop_index('servizio_id', 'dipendente_servizio')
    safe_drop_table('dipendente_servizio')
    safe_drop_table('servizio_documentazione')
    safe_drop_index('codice_notarile', 'notai')
    safe_drop_table('notai')
    safe_drop_index('ix_documentazioni_id', 'documentazioni')
    safe_drop_table('documentazioni')
    safe_drop_index('ix_clienti_id', 'clienti')
    safe_drop_index('utente_id', 'clienti')
    safe_drop_table('clienti')
    safe_drop_index('ix_servizi_id', 'servizi')
    safe_drop_table('servizi')
    safe_drop_index('ix_users_email', 'users')
    safe_drop_index('ix_users_id', 'users')
    safe_drop_table('users')
    safe_drop_index('utente_id', 'dipendenti_tecnici')
    safe_drop_table('dipendenti_tecnici')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clienti',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('utente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['utente_id'], ['users.id'], name='clienti_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('utente_id'), 'clienti', ['utente_id'], unique=True)
    op.create_index(op.f('ix_clienti_id'), 'clienti', ['id'], unique=False)
    op.create_table('servizio_documentazione',
    sa.Column('servizio_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('documentazione_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['documentazione_id'], ['documentazioni.id'], name=op.f('servizio_documentazione_ibfk_2')),
    sa.ForeignKeyConstraint(['servizio_id'], ['servizi.id'], name=op.f('servizio_documentazione_ibfk_1')),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('cognome', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('numeroTelefonico', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('ruolo', mysql.ENUM('CLIENTE', 'NOTAIO', 'DIPENDENTE'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('servizi',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codiceCorrente', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codiceServizio', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dataConsegna', mysql.DATETIME(), nullable=False),
    sa.Column('dataRichiesta', mysql.DATETIME(), nullable=False),
    sa.Column('statoServizio', mysql.ENUM('CREATO', 'IN_LAVORAZIONE', 'IN_ATTESA_APPROVAZIONE', 'APPROVATO', 'RIFIUTATO', 'CONSEGNATO'), server_default=sa.text("'CREATO'"), nullable=False),
    sa.Column('tipo', mysql.ENUM('ATTO', 'COMPROMESSO', 'PREVENTIVO'), nullable=False),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('dipendente_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], name='servizi_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_servizi_id'), 'servizi', ['id'], unique=False)
    op.create_table('notai',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codice_notarile', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['dipendenti_tecnici.id'], name=op.f('fk_notai_dipendente')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('codice_notarile'), 'notai', ['codice_notarile'], unique=True)
    op.create_table('dipendente_cliente',
    sa.Column('dipendente_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], name=op.f('dipendente_cliente_ibfk_2')),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendenti_tecnici.id'], name=op.f('dipendente_cliente_ibfk_1')),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dipendente_servizio',
    sa.Column('dipendente_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('servizio_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendenti_tecnici.id'], name=op.f('dipendente_servizio_ibfk_1')),
    sa.ForeignKeyConstraint(['servizio_id'], ['servizi.id'], name=op.f('dipendente_servizio_ibfk_2')),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('documentazioni',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('tipo', mysql.ENUM('CARTA_IDENTITA', 'DOCUMENTO_PROPRIETA', 'PASSAPORTO', 'VISURE_CATASTALI', 'PLANIMETRIA', 'ATTO', 'COMPROMESSO', 'PREVENTIVO'), nullable=False),
    sa.Column('path', mysql.VARCHAR(collation='utf8mb4_general_ci', length=1024), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], name=op.f('documentazioni_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_documentazioni_id'), 'documentazioni', ['id'], unique=False)
    op.create_table('dipendenti_tecnici',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('utente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', mysql.ENUM('NOTAIO', 'CONTABILE', 'ASSISTENTE', 'DIPENDENTE'), server_default=sa.text("'DIPENDENTE'"), nullable=False),
    sa.ForeignKeyConstraint(['utente_id'], ['users.id'], name=op.f('dipendenti_tecnici_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('utente_id'), 'dipendenti_tecnici', ['utente_id'], unique=True)
    # ### end Alembic commands ###
